### ISSUE TITLE
VoiceFalloffAdjMod doesn't seem to work

### ISSUE THREAD

**Issue by SwizzlestixUK** [Nirv-git/CVRMods-Nirv#1]
This mod in particular doesn't seem to do anything for anyone I know personally who has it installed. The slider does not affect voice falloff distance; if a dependency is required for this mod to function properly, can I request what that is?

On that note, can I request that dependencies for each mod be included in the readme somewhere? (IE. CVRUIModLoader required for any mod menu functions) Some users aren't knowledgeable enough to make the link that it's required, and there's no indication of such otherwise, especially in the CVRMelonAssistant interface.

Thanks in advance!

**Comment by Nirv-git** [comment]
Did you have this button turned on? It toggles the mod functionality. 
![image](https://user-images.githubusercontent.com/81605232/188247443-b331014a-631f-4e79-a130-fd81923e5f00.png)
I may want to switch out the icon for that, as it isn't super obvious that it is a toggle (had one or two people message me that)


None of the mods currently here should require any dependencies, certainly not CVRUIModLoader

**Comment by SwizzlestixUK** [comment]
Oh, okay. I'll try the mod again without CVRUIML, apologies for that.
I didn't realise it was a toggle! I'll be sure to try that out next time too. Thanks!
