### ISSUE TITLE
[PortableMirror] Errors during mod initialization

### ISSUE THREAD

**Issue by kafeijao** [Nirv-git/CVRMods-Nirv#2]
![image](https://user-images.githubusercontent.com/4409693/192108503-91f91225-c434-4bc5-8dde-cf6256b4b9ae.png)

I'm getting some errors during other mods initialization, I was looking for the issue at it seems it happens when `OnPreferencesSaved` is called (because another mod saved prefs for example) and PortableMirror's `OnApplicationStart` wasn't called yet.

The NullReferenceException is coming from https://github.com/Nirv-git/CVRMods-Nirv/blob/c4f50d11cb858a2d0366e0655801da3d985cea93/PortableMirror_Combined/Main.cs#L249

Because `distanceDisable` was not initialized yet.

**Comment by Nirv-git** [comment]
Bah, why must some mods call a global OnPrefSave on init, if they want they can just call their own OnPrefSav method.   
   
Will fix in next version

**Comment by NotAKidOnSteam** [comment]
heh- all my mods used to save preferences on startup 

sdraw chewed me out for that~
