### ISSUE TITLE
[SitLaydown] Position doesn't maintain

### ISSUE THREAD

**Issue by componentxxxx** [Nirv-git/CVRMods-Nirv#4]
The chair button works the first time around every time i launch the game, but if i unselect it or accidentally press a movement bind that gets me out of it, the next time i try to re"chair", the position is off, broken even, my feet are at an angle and even if i adjust my head height manually with playspace, the hip area stays at an angle. Even if I don't touch playspace, it puts me under the floor the next time i press the chair, which i have to hotfix by using seated mode (it keeps me under the floor if i toggle it back off) or have to refresh the avatar/switch to fix that, but then have to refrain from chairing again, lest i have to fix it again/use the arrows mid chair

**Comment by Nirv-git** [comment]
Just an update, CVR 2023r173 fixed some stuff with chairs, and much of this mod was rewritten recently to be more user friendly 
https://github.com/Nirv-git/CVRMods-Nirv/releases/tag/SitLay1.1.1_IKpreset0.5.4
