### ISSUE TITLE
can not use [sitlaydown] mod

### ISSUE THREAD

**Issue by sophienix** [Nirv-git/CVRMods-Nirv#6]
i cant use sitlaydown mod i cant seem to find the button menue for ir

**Comment by Nirv-git** [comment]
What version of CVR are you running, Stable or Experimental?    
   
For [SitLaydown](https://api.cvrmg.com/v1/mods/download/88) make sure you also have [BTKUILib](https://api.cvrmg.com/v1/mods/download/113) installed    

If you want to post your Lastest.log here, or in the CVRMG Discord #help-and-support channel we can look deeper into it. 
The log can be found at `steamapps\common\ChilloutVR\MelonLoader\Latest.log`
